apiVersion: v1
kind: Service
metadata:
  name: nginx-blue-green-svc
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: nginx
    version: {{ .Values.active }}