{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-tls
  labels:
    app: {{ .Chart.Name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "certs/cert.pem" | b64enc }}
  tls.key: {{ .Files.Get "certs/key.pem" | b64enc }}
{{- end }}